### ISSUE TITLE
node 16+ limitation

### ISSUE THREAD

**Issue by StanislavMayorov** [darleikroth/react-native-android-keyboard-adjust#10]
Hello! Thank you for the repo. There's requirements `"node": ">= 16.0.0"`, but I tested with v14 and it worked okay. Could you remove this limitation please?
https://github.com/darleikroth/rn-android-keyboard-adjust/blob/master/package.json#L82

**Comment by darleikroth** [comment]
Hi.
Some requirements are necessary for the CI process. Node 16+ is one of them.

**Comment by StanislavMayorov** [comment]
It's not very convenient because RN support node v14. Thank you for reply.
