### ISSUE TITLE
Unable to resolve module rn-android-keyboard-adjust/index

### ISSUE THREAD

**Issue by Arnav7501** [darleikroth/react-native-android-keyboard-adjust#11]
When attempting to run my app, I get this error:
Error: Unable to resolve module rn-android-keyboard-adjust/index from /Users/arnavchowdhry/Downloads/mobile-client-main/Persona/src/components/ActivityChatScreen.js: rn-android-keyboard-adjust/index could not be found within the project or in these directories:
  node_modules
  ../../../node_modules
   6 | import firestore from '@react-native-firebase/firestore';
   7 | import {SYSTEM_DM_PERSONA_ID} from '../sys/personas';
>  8 | import RNAndroidKeyboardAdjust from 'rn-android-keyboard-adjust/index';

System info:
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 107.75 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/Downloads/mobile-client-main/Persona/node_modules/.bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2
      System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: >=0.70.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by darleikroth** [comment]
Did you try the usage guide?

[Usage](https://github.com/darleikroth/rn-android-keyboard-adjust#usage)

I did a test by creating a new react-native app:

`npx react-native@latest init apptest`
`npm i -S rn-android-keyboard-adjust`

And it's working properly.
